server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dupeng5/configServer.git
          search-paths: mybatis
          username: dupeng5
          password: Dp651342298